apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: formation-mlops-api
spec:
  project: default
  source:
    repoURL: https://github.com/rayaberova7/formation-mlops.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: user-rayaberova
  syncPolicy:
    automated:
      selfHeal: true
